### ISSUE TITLE
Embeddings in EmbeddingKMeans and ContrastiveActiveLearning

### ISSUE THREAD

**Issue by kayuksel** [webis-de/small-text#13]
Hi! Do they support embeddings from a language-agnostic model like LabSE or XLM-RoBERTa? (as this is not the case in their papers). Would it be possible to use any embeddings that we previously extract with those methods? If so, how we can do that?  I believe that this could be very crucial for this library for not limiting its use to only English-language or any specific encoder.

**Comment by chschroeder** [comment]
Hi @kayuksel, as for the general capabilities, I don't see any language or encoder limitations so far, and I fully share your opinion on this. 

I am no expert on either one of these models but I assume you want to use the [sentence transformer model](https://huggingface.co/sentence-transformers/LaBSE) for LabSE and the [huggingface implementation](https://huggingface.co/xlm-roberta-large) of XLM-Roberta, is this correct? 

The latter is easy, you could take [the example notebook](https://github.com/webis-de/small-text/blob/35a74fb1288463c2ae5a957c29774b77a644f52e/examples/notebooks/01-active-learning-for-text-classification-with-small-text-intro.ipynb) and it should be enough to pass the transformer model name for the respective XLM (e.g., `xlm-roberta-large`).

For the former, you would also just need a slightly different [preprocessing](https://github.com/webis-de/small-text/blob/35a74fb1288463c2ae5a957c29774b77a644f52e/examples/examplecode/data/example_data_transformers.py#L6), which requires just a few lines of code. Other than that it should work fine (because everything is an embedding at this point as you correctly mentioned). The same is true if you want to use pre-computed embeddings. Let me know if you encounter problems with this. Sentence transformers could likely get a better support in the coming months.

**Comment by kayuksel** [comment]
HuggingFace implementations would be sufficient I believe.

Note: I actually found a [distilled version of XLM-Robeta-Large](https://huggingface.co/nreimers/mMiniLMv2-L12-H384-distilled-from-XLMR-Large).
