### ISSUE TITLE
Query by committee-of-committees

### ISSUE THREAD

**Issue by vahuja4** [webis-de/small-text#28]
For example, you could compute the confidence score, the margin, and the entropy for all of the records in the remaining pool, and then pick the records that are selected the most out of those querying strategies.

Has anyone tried this and could you share your experience please?

**Comment by chschroeder** [comment]
Not sure if I am correctly following here. I see the committee in your question, but I don't see where the comittee-of-committee is.

That being said, I do not even use committees right now because runtime is already an important factor when using recent transformer-based models. Committees of committees would be even more computationally expensive.

I already thought about adding a committee strategy to small-text but this is very low priority right now.
